name: HeadNSeek
version: ${version}
api-version: "${minecraft_version}"
main: de.greensurvivors.headnseek.paper.HeadNSeek
author: GreenSurvivorsTeam
loader: de.greensurvivors.headnseek.paper.startup.PaperPluginLoader
dependencies:
  server:
    GreenSocket:
      load: BEFORE
      required: false